name: tp1
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672 # For Clients AMQP
      - 15672:15672 # For RabbitMQ Management UI
    networks:
      - movies_net
    logging:
      driver: none

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - CLI_LOG_LEVEL=info
      - SERVER_PORT=3000
      - SERVER_LISTEN_BACKLOG=1
      - CLI_WORKER_EXCHANGE_INPUT_NAME=results_exchange
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=queries_partial_results.input
      - CLI_WORKER_EXCHANGE1_OUTPUT_NAME=first_layer_exchange
      - CLI_WORKER_EXCHANGE1_OUTPUT_ROUTINGKEYS=movies.first.input1,movies.first.input2
      - CLI_WORKER_EXCHANGE2_OUTPUT_NAME=query4_exchange
      - CLI_WORKER_EXCHANGE2_OUTPUT_ROUTINGKEYS=credits.input
      - CLI_WORKER_EXCHANGE3_OUTPUT_NAME=query3_exchange
      - CLI_WORKER_EXCHANGE3_OUTPUT_ROUTINGKEYS=ratings.input
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
    container_name: server
    image: server:latest
    entrypoint: python main.py
    networks:
      - movies_net
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
    logging:
      driver: none

  machine_learning-1:
    container_name: machine_learning-1
    image: machine_learning:latest
    volumes:
      - ./machine_learning:/app
    environment:
      - CLI_LOG_LEVEL=info
      - CLI_WORKER_EXCHANGE_INPUT_NAME=first_layer_exchange
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=movies.first.input1
      - CLI_WORKER_EXCHANGE_OUTPUT_NAME=ml_group_by_overview_exchange
      - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=group_by_movie_average.input1,group_by_movie_average.input2
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_WORKER_QUEUE_NAME=movies.only_one_country.input.1
    networks:
      - movies_net
    depends_on:
      - rabbitmq

  machine_learning-2:
    container_name: machine_learning-2
    image: machine_learning:latest
    volumes:
      - ./machine_learning:/app
    environment:
      - CLI_LOG_LEVEL=info
      - CLI_WORKER_EXCHANGE_INPUT_NAME=first_layer_exchange
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=movies.first.input2
      - CLI_WORKER_EXCHANGE_OUTPUT_NAME=ml_group_by_overview_exchange
      - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=group_by_movie_average.input1,group_by_movie_average.input2
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_WORKER_QUEUE_NAME=movies.only_one_country.input.2
    networks:
      - movies_net
    depends_on:
      - rabbitmq

  group_by_overview_average-1:
    build:
      context: .
      dockerfile: group_by/group_by_overview_average/Dockerfile
    container_name: group_by_overview_average-1
    image: group_by_overview_average:latest
    environment:
      - CLI_LOG_LEVEL=info
      - CLI_WORKER_EXCHANGE_INPUT_NAME=ml_group_by_overview_exchange
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=group_by_movie_average.input1
      - CLI_WORKER_EXCHANGE_OUTPUT_NAME=group_by-master_group_by
      - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=master_group_by_movie_average.input
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_WORKER_QUEUE_NAME=group_by_country_sum.input1
      - CLI_WORKER_MAXMESSAGES=10
      - CLI_WORKER_EXPECTEDEOF=2
    entrypoint: ./run_worker
    networks:
      - movies_net
    depends_on:
      - rabbitmq

  group_by_overview_average-2:
    build:
      context: .
      dockerfile: group_by/group_by_overview_average/Dockerfile
    container_name: group_by_overview_average-2
    image: group_by_overview_average:latest
    environment:
      - CLI_LOG_LEVEL=info
      - CLI_WORKER_EXCHANGE_INPUT_NAME=ml_group_by_overview_exchange
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=group_by_movie_average.input2
      - CLI_WORKER_EXCHANGE_OUTPUT_NAME=group_by-master_group_by
      - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=master_group_by_movie_average.input
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_WORKER_QUEUE_NAME=group_by_country_sum.input2
      - CLI_WORKER_MAXMESSAGES=10
      - CLI_WORKER_EXPECTEDEOF=2
    entrypoint: ./run_worker
    networks:
      - movies_net
    depends_on:
      - rabbitmq

  master_group_by_overview_average:
    build:
      context: .
      dockerfile: master_group_by/master_group_by_overview_average/Dockerfile
    container_name: master_group_by_overview_average
    image: master_group_by_overview_average:latest
    environment:
      - CLI_LOG_LEVEL=info
      - CLI_WORKER_EXCHANGE_INPUT_NAME=group_by-master_group_by
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=master_group_by_movie_average.input
      - CLI_WORKER_EXCHANGE_OUTPUT_NAME=results_exchange
      - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=queries_partial_results.input
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_WORKER_MAXMESSAGES=10
      - CLI_WORKER_EXPECTEDEOF=2
    entrypoint: ./run_worker
    networks:
      - movies_net
    depends_on:
      - rabbitmq

networks:
  movies_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
