name: tp1
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672 # For Clients AMQP
      - 15672:15672 # For RabbitMQ Management UI
    networks:
      - movies_net
    logging:
      driver: none

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - CLI_LOG_LEVEL=info
      - SERVER_PORT=3000
      - SERVER_LISTEN_BACKLOG=1
      - CLI_WORKER_EXCHANGE_INPUT_NAME=results_exchange
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=queries_partial_results.input
      - CLI_WORKER_EXCHANGE1_OUTPUT_NAME=first_layer_exchange
      - CLI_WORKER_EXCHANGE1_OUTPUT_ROUTINGKEYS=movies.first.input1,movies.first.input2
      - CLI_WORKER_EXCHANGE2_OUTPUT_NAME=query4_exchange
      - CLI_WORKER_EXCHANGE2_OUTPUT_ROUTINGKEYS=credits.input
      - CLI_WORKER_EXCHANGE3_OUTPUT_NAME=query3_exchange
      - CLI_WORKER_EXCHANGE3_OUTPUT_ROUTINGKEYS=ratings.input
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
    container_name: server
    image: server:latest
    entrypoint: python main.py
    networks:
      - movies_net
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
    logging:
      driver: none

  filter-argentina-1:
    build:
      context: .
      dockerfile: filters/filter_argentina/Dockerfile
    container_name: filter-argentina-1
    image: filter-argentina:latest
    environment:
      - CLI_LOG_LEVEL=info
      - CLI_WORKER_EXCHANGE_INPUT_NAME=first_layer_exchange
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=movies.first.input1
      - CLI_WORKER_EXCHANGE_OUTPUT_NAME=movies_filtered_by_argentina_exchange
      - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=movies.spain_2000_1.input,movies.spain_2000_2.input
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_WORKER_EXPECTEDEOF=1
      - CLI_WORKER_QUEUE_NAME=movies.argentina.input.1
    entrypoint: ./run_worker
    networks:
      - movies_net
    depends_on:
      - rabbitmq

  filter-argentina-2:
    build:
      context: .
      dockerfile: filters/filter_argentina/Dockerfile
    container_name: filter-argentina-2
    image: filter-argentina-2:latest
    environment:
      - CLI_LOG_LEVEL=info
      - CLI_WORKER_EXCHANGE_INPUT_NAME=first_layer_exchange
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=movies.first.input2
      - CLI_WORKER_EXCHANGE_OUTPUT_NAME=movies_filtered_by_argentina_exchange
      - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=movies.spain_2000_1.input,movies.spain_2000_2.input
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_WORKER_EXPECTEDEOF=1
      - CLI_WORKER_QUEUE_NAME=movies.argentina.input.2
    entrypoint: ./run_worker
    networks:
      - movies_net
    depends_on:
      - rabbitmq

  filter-spain-2000-1:
    build:
      context: .
      dockerfile: filters/filter_spain_2000/Dockerfile
    container_name: filter-spain-2000-1
    image: filter-spain-2000:latest
    environment:
      - CLI_LOG_LEVEL=info
      - CLI_WORKER_EXCHANGE_INPUT_NAME=movies_filtered_by_argentina_exchange
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=movies.spain_2000_1.input
      - CLI_WORKER_EXCHANGE_OUTPUT_NAME=results_exchange
      - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=queries_partial_results.input
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_WORKER_EXPECTEDEOF=2
      - CLI_WORKER_QUEUE_NAME=movies.spain_2000_1.input
    entrypoint: ./run_worker
    networks:
      - movies_net
    depends_on:
      - rabbitmq

  filter-spain-2000-2:
    build:
      context: .
      dockerfile: filters/filter_spain_2000/Dockerfile
    container_name: filter-spain-2000-2
    image: filter-spain-2000-2:latest
    environment:
      - CLI_LOG_LEVEL=info
      - CLI_WORKER_EXCHANGE_INPUT_NAME=movies_filtered_by_argentina_exchange
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=movies.spain_2000_2.input
      - CLI_WORKER_EXCHANGE_OUTPUT_NAME=results_exchange
      - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=queries_partial_results.input
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_WORKER_EXPECTEDEOF=2
      - CLI_WORKER_QUEUE_NAME=movies.spain_2000_2.input
    entrypoint: ./run_worker
    networks:
      - movies_net
    depends_on:
      - rabbitmq

networks:
  movies_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
