name: tp1
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672 # For Clients AMQP
      - 15672:15672 # For RabbitMQ Management UI
    networks:
      - movies_net

  filter-after-2000:
    build:
      context: .
      dockerfile: filters/Dockerfile
    container_name: filter-after-2000
    image: filter-after-2000:latest
    environment:
      - FILTER_NAME=filter_after_2000
      - LOG_LEVEL=info
      - WORKER_EXCHANGE_INPUT=input_exchange
      - WORKER_EXCHANGE_OUTPUT=output_exchange
      - WORKER_BROKER=amqp://guest:guest@localhost:5672/
    entrypoint: ./filter_runner
    networks:
      - movies_net
    depends_on:
      - rabbitmq

  filter-argentina:
    build:
      context: .
      dockerfile: filters/Dockerfile
    container_name: filter-argentina
    image: filter-argentina:latest
    environment:
      - FILTER_NAME=filter_argentina
      - LOG_LEVEL=info
      - WORKER_EXCHANGE_INPUT=input_exchange
      - WORKER_EXCHANGE_OUTPUT=output_exchange
      - WORKER_BROKER=amqp://guest:guest@localhost:5672/
    entrypoint: ./filter_runner
    networks:
      - movies_net
    depends_on:
      - rabbitmq

  filter-spain-2000:
    build:
      context: .
      dockerfile: filters/Dockerfile
    container_name: filter-spain-2000
    image: filter-spain-2000:latest
    environment:
      - FILTER_NAME=filter_spain_2000
      - LOG_LEVEL=info
      - WORKER_EXCHANGE_INPUT=input_exchange
      - WORKER_EXCHANGE_OUTPUT=output_exchange
      - WORKER_BROKER=amqp://guest:guest@localhost:5672/
    entrypoint: ./filter_runner
    networks:
      - movies_net
    depends_on:
      - rabbitmq

  filter-only-one-country:
    build:
      context: .
      dockerfile: filters/Dockerfile
    container_name: filter-only-one-country
    image: filter-only-one-country:latest
    environment:
      - FILTER_NAME=filter_only_one_country
      - LOG_LEVEL=info
      - WORKER_EXCHANGE_INPUT=input_exchange
      - WORKER_EXCHANGE_OUTPUT=output_exchange
      - WORKER_BROKER=amqp://guest:guest@localhost:5672/
    entrypoint: ./filter_runner
    networks:
      - movies_net
    depends_on:
      - rabbitmq

  group_by_country_sum:
    build:
      context: .
      dockerfile: group_by/group_by_country_sum/Dockerfile
    volumes:
      - ./group_by/group_by_country_sum/main/config.yaml:/config.yaml
    container_name: group_by_country_sum
    image: group_by_country_sum:latest
    entrypoint: ./group_by_country_sum
    networks:
      - movies_net
    depends_on:
      - rabbitmq

  top_five_country_budget:
    build:
      context: .
      dockerfile: topn/top_five_country_budget/Dockerfile
    volumes:
      - ./topn/top_five_country_budget/main/config.yaml:/config.yaml
    container_name: top_five_country_budget
    image: top_five_country_budget:latest
    entrypoint: ./top_five_country_budget
    networks:
      - movies_net
    depends_on:
      - rabbitmq

  join_movie_credits:
    build:
      context: .
      dockerfile: joins/join_movie_credits/Dockerfile
    volumes:
      - ./joins/join_movie_credits/main/config.yaml:/config.yaml
    container_name: join_movie_credits
    image: join_movie_credits:latest
    entrypoint: ./join_movie_credits
    networks:
      - movies_net
    depends_on:
      - rabbitmq

  join_movie_ratings:
    build:
      context: .
      dockerfile: joins/join_movie_ratings/Dockerfile
    volumes:
      - ./joins/join_movie_ratings/main/config.yaml:/config.yaml
    container_name: join_movie_ratings
    image: join_movie_ratings:latest
    entrypoint: ./join_movie_ratings
    networks:
      - movies_net
    depends_on:
      - rabbitmq

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - WORKER_BROKER=rabbitmq
      - SERVER_PORT=3000
      - SERVER_LISTEN_BACKLOG=1
      - LOGGING_LEVEL=info
    container_name: server
    image: server:latest
    entrypoint: python3 main.py
    networks:
      - movies_net
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq

networks:
  movies_net:
    ipam:
      driver: default
