name: tp1
networks:
  movies_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    networks: &id001
      - movies_net
    ports:
      - 5672:5672
      - 15672:15672
    logging:
      driver: none
  client-handler:
    container_name: client-handler
    build:
      context: .
      dockerfile: client-handler/Dockerfile
    image: client-handler:latest
    entrypoint: python main.py
    networks: *id001
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
    environment:
      - CLIENT_HANDLER_PORT=3000
      - LOGGING_LEVEL=info
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLIENT_HANDLER_LISTEN_BACKLOG=5
      - INPUT_ROUTINGKEY=*.results
      - OUTPUT_ROUTINGKEYS_FILTER_ARG=filter-argentina.1
      - OUTPUT_ROUTINGKEYS_FILTER_ONE_COUNTRY=filter-only-one-country.1
      - OUTPUT_ROUTINGKEYS_JOIN_MOVIES_RATING=join-ratings.1
      - OUTPUT_ROUTINGKEYS_JOIN_MOVIES_CREDITS=join-credits.1
  filter-argentina-1:
    build:
      context: .
      dockerfile: filters/filter_argentina/Dockerfile
    container_name: filter-argentina-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - ROUTINGKEYS_INPUT=filter-argentina.1
      - ROUTINGKEYS_OUTPUT_FILTER-SPAIN-2000=filter-spain-2000.1
      - ROUTINGKEYS_OUTPUT_FILTER-AFTER-2000=filter-after-2000.1
    image: filter_argentina:latest
    networks:
      - movies_net
  filter-spain-2000-1:
    build:
      context: .
      dockerfile: filters/filter_spain_2000/Dockerfile
    container_name: filter-spain-2000-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - ROUTINGKEYS_INPUT=filter-spain-2000.1
      - ROUTINGKEYS_OUTPUT_OUTPUT_ROUTINGKEY=query1.results
    image: filter_spain_2000:latest
    networks:
      - movies_net
  filter-only-one-country-1:
    build:
      context: .
      dockerfile: filters/filter_only_one_country/Dockerfile
    container_name: filter-only-one-country-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - ROUTINGKEYS_INPUT=filter-only-one-country.1
      - ROUTINGKEYS_OUTPUT_GROUP-BY-COUNTRY-SUM=group-by-country-sum.1
    image: filter_only_one_country:latest
    networks:
      - movies_net
  filter-after-2000-1:
    build:
      context: .
      dockerfile: filters/filter_after_2000/Dockerfile
    container_name: filter-after-2000-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - ROUTINGKEYS_INPUT=filter-after-2000.1
      - ROUTINGKEYS_OUTPUT_JOIN-MOVIE-RATINGS=join-movie-ratings.1
      - ROUTINGKEYS_OUTPUT_JOIN-MOVIE-CREDITS=join-movie-credits.1
    image: filter_after_2000:latest
    networks:
      - movies_net
  group-by-country-sum-1:
    build:
      context: .
      dockerfile: group_by/group_by_country_sum/Dockerfile
    container_name: group-by-country-sum-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - EOF_COUNTER=1
      - ROUTINGKEYS_INPUT=group-by-country-sum.1
      - ROUTINGKEYS_OUTPUT_MASTER-GROUP-BY-COUNTRY-SUM=master-group-by-country-sum.1
      - CLI_WORKER_STORAGE=/app/storage
      - CLI_WORKER_MAXMESSAGES=10
    image: group_by_country_sum:latest
    networks:
      - movies_net
    volumes:
      - .local-storage/group-by-country-sum-1:/app/storage
  group-by-movie-average-1:
    build:
      context: .
      dockerfile: group_by/group_by_movie_average/Dockerfile
    container_name: group-by-movie-average-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - EOF_COUNTER=1
      - ROUTINGKEYS_INPUT=group-by-movie-average.1
      - ROUTINGKEYS_OUTPUT_MASTER-GROUP-BY-MOVIE-AVERAGE=master-group-by-movie-average.1
      - CLI_WORKER_STORAGE=/app/storage
      - CLI_WORKER_MAXMESSAGES=10
    image: group_by_movie_average:latest
    networks:
      - movies_net
    volumes:
      - .local-storage/group-by-movie-average-1:/app/storage
  group-by-actor-count-1:
    build:
      context: .
      dockerfile: group_by/group_by_actor_count/Dockerfile
    container_name: group-by-actor-count-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - EOF_COUNTER=1
      - ROUTINGKEYS_INPUT=group-by-actor-count.1
      - ROUTINGKEYS_OUTPUT_MASTER-GROUP-BY-ACTOR-COUNT=master-group-by-actor-count.1
      - CLI_WORKER_STORAGE=/app/storage
      - CLI_WORKER_MAXMESSAGES=10
    image: group_by_actor_count:latest
    networks:
      - movies_net
    volumes:
      - .local-storage/group-by-actor-count-1:/app/storage
  group-by-overview-average-1:
    build:
      context: .
      dockerfile: group_by/group_by_overview_average/Dockerfile
    container_name: group-by-overview-average-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - EOF_COUNTER=1
      - ROUTINGKEYS_INPUT=group-by-overview-average.1
      - ROUTINGKEYS_OUTPUT_MASTER-GROUP-BY-OVERVIEW-AVERAGE=master-group-by-overview-average.1
      - CLI_WORKER_STORAGE=/app/storage
      - CLI_WORKER_MAXMESSAGES=10
    image: group_by_overview_average:latest
    networks:
      - movies_net
    volumes:
      - .local-storage/group-by-overview-average-1:/app/storage
  master-group-by-country-sum-1:
    build:
      context: .
      dockerfile: master_group_by/master_group_by_country_sum/Dockerfile
    container_name: master-group-by-country-sum-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - EOF_COUNTER=1
      - ROUTINGKEYS_INPUT=master-group-by-country-sum.1
      - ROUTINGKEYS_OUTPUT_TOP-FIVE-COUNTRY-BUDGET=top-five-country-budget.1
      - CLI_WORKER_STORAGE=/app/storage
      - CLI_WORKER_MAXMESSAGES=1
    image: master_group_by_country_sum:latest
    networks:
      - movies_net
    volumes:
      - .local-storage/master-group-by-country-sum-1:/app/storage
  master-group-by-movie-average-1:
    build:
      context: .
      dockerfile: master_group_by/master_group_by_movie_average/Dockerfile
    container_name: master-group-by-movie-average-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - EOF_COUNTER=1
      - ROUTINGKEYS_INPUT=master-group-by-movie-average.1
      - ROUTINGKEYS_OUTPUT_FIRST-AND-LAST=first-and-last.1
      - CLI_WORKER_STORAGE=/app/storage
      - CLI_WORKER_MAXMESSAGES=1
    image: master_group_by_movie_average:latest
    networks:
      - movies_net
    volumes:
      - .local-storage/master-group-by-movie-average-1:/app/storage
  master-group-by-actor-count-1:
    build:
      context: .
      dockerfile: master_group_by/master_group_by_actor_count/Dockerfile
    container_name: master-group-by-actor-count-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - EOF_COUNTER=1
      - ROUTINGKEYS_INPUT=master-group-by-actor-count.1
      - ROUTINGKEYS_OUTPUT_TOP-TEN-CAST-MOVIE=top-ten-cast-movie.1
      - CLI_WORKER_STORAGE=/app/storage
      - CLI_WORKER_MAXMESSAGES=1
    image: master_group_by_actor_count:latest
    networks:
      - movies_net
    volumes:
      - .local-storage/master-group-by-actor-count-1:/app/storage
  master-group-by-overview-average-1:
    build:
      context: .
      dockerfile: master_group_by/master_group_by_overview_average/Dockerfile
    container_name: master-group-by-overview-average-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - EOF_COUNTER=1
      - ROUTINGKEYS_INPUT=master-group-by-overview-average.1
      - ROUTINGKEYS_OUTPUT_OUTPUT_ROUTINGKEY=query5.results
      - CLI_WORKER_STORAGE=/app/storage
      - CLI_WORKER_MAXMESSAGES=1
    image: master_group_by_overview_average:latest
    networks:
      - movies_net
    volumes:
      - .local-storage/master-group-by-overview-average-1:/app/storage
  machine-learning-1:
    build:
      context: .
      dockerfile: machine_learning/Dockerfile
    container_name: machine-learning-1
    depends_on:
      - rabbitmq
    entrypoint: python main.py
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - ROUTINGKEYS_INPUT=machine-learning.1
      - ROUTINGKEYS_OUTPUT_GROUP-BY-OVERVIEW-AVERAGE=group-by-overview-average.1
    image: machine_learning:latest
    networks:
      - movies_net
  top-five-country-budget-1:
    build:
      context: .
      dockerfile: topn/top_five_country_budget/Dockerfile
    container_name: top-five-country-budget-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - ROUTINGKEYS_INPUT=top-five-country-budget.1
      - ROUTINGKEYS_OUTPUT_OUTPUT_ROUTINGKEY=query2.results
      - CLI_WORKER_STORAGE=/app/storage
      - CLI_WORKER_MAXMESSAGES=10
    image: top_five_country_budget:latest
    networks:
      - movies_net
    volumes:
      - .local-storage/top-five-country-budget-1:/app/storage
  top-ten-cast-movie-1:
    build:
      context: .
      dockerfile: topn/top_ten_cast_movie/Dockerfile
    container_name: top-ten-cast-movie-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - ROUTINGKEYS_INPUT=top-ten-cast-movie.1
      - ROUTINGKEYS_OUTPUT_OUTPUT_ROUTINGKEY=query4.results
      - CLI_WORKER_STORAGE=/app/storage
      - CLI_WORKER_MAXMESSAGES=10
    image: top_ten_cast_movie:latest
    networks:
      - movies_net
    volumes:
      - .local-storage/top-ten-cast-movie-1:/app/storage
  # join-movie-ratings-1:
  #   build:
  #     context: .
  #     dockerfile: joins/join_movie_ratings/Dockerfile
  #   container_name: join-movie-ratings-1
  #   depends_on:
  #     - rabbitmq
  #   entrypoint: ./run_worker
  #   environment:
  #     - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
  #     - CLI_LOG_LEVEL=info
  #     - EOF_COUNTER=1
  #     - ROUTINGKEYS_INPUT=join-movie-ratings.1,join-ratings.1
  #     - ROUTINGKEYS_OUTPUT_GROUP-BY-MOVIE-AVERAGE=group-by-movie-average.1
  #     - CLI_WORKER_STORAGE=/app/storage
  #   image: join_movie_ratings:latest
  #   networks:
  #     - movies_net
  #   volumes:
  #     - .local-storage/join-movie-ratings-1:/app/storage
  # join-movie-credits-1:
  #   build:
  #     context: .
  #     dockerfile: joins/join_movie_credits/Dockerfile
  #   container_name: join-movie-credits-1
  #   depends_on:
  #     - rabbitmq
  #   entrypoint: ./run_worker
  #   environment:
  #     - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
  #     - CLI_LOG_LEVEL=info
  #     - EOF_COUNTER=1
  #     - ROUTINGKEYS_INPUT=join-movie-credits.1,join-credits.1
  #     - ROUTINGKEYS_OUTPUT_GROUP-BY-ACTOR-COUNT=group-by-actor-count.1
  #     - CLI_WORKER_STORAGE=/app/storage
  #   image: join_movie_credits:latest
  #   networks:
  #     - movies_net
  #   volumes:
  #     - .local-storage/join-movie-credits-1:/app/storage
  first-and-last-1:
    build:
      context: .
      dockerfile: topn/first_and_last/Dockerfile
    container_name: first-and-last-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - ROUTINGKEYS_INPUT=first-and-last.1
      - ROUTINGKEYS_OUTPUT_OUTPUT_ROUTINGKEY=query3.results
      - CLI_WORKER_STORAGE=/app/storage
      - CLI_WORKER_MAXMESSAGES=10
    image: first_and_last:latest
    networks:
      - movies_net
    volumes:
      - .local-storage/first-and-last-1:/app/storage
