version: "3.8"
name: tp1
networks:
  movies_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    networks: &id001
      - movies_net
    ports:
      - 5672:5672
      - 15672:15672
    logging:
      driver: none
  client-handler:
    container_name: client-handler
    build:
      context: .
      dockerfile: client-handler/Dockerfile
    image: client-handler:latest
    entrypoint: python main.py
    networks: *id001
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
    environment:
      - CLIENT_HANDLER_PORT=3000
      - LOGGING_LEVEL=info
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLIENT_HANDLER_LISTEN_BACKLOG=5
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=*.results
      - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=movies.client_handler,ratings.client-handler.router,credits.client-handler.router
  filter-argentina-1:
    build:
      context: .
      dockerfile: filters/filter_argentina/Dockerfile
    container_name: filter-argentina-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=movies.client_handler
      - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=movies.argentina
    image: filter_argentina:latest
    networks:
      - movies_net
  filter-spain-2000-1:
    build:
      context: .
      dockerfile: filters/filter_spain_2000/Dockerfile
    container_name: filter-spain-2000-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=movies.argentina
      - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=query1.results
    image: filter_spain_2000:latest
    networks:
      - movies_net
  filter-only-one-country-1:
    build:
      context: .
      dockerfile: filters/filter_only_one_country/Dockerfile
    container_name: filter-only-one-country-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=movies.client_handler
      - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=movies.filter_only_one_country.router
    image: filter_only_one_country:latest
    networks:
      - movies_net
  filter-after-2000-1:
    build:
      context: .
      dockerfile: filters/filter_after_2000/Dockerfile
    container_name: filter-after-2000-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=movies.argentina
      - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=movies.after_2000
    image: filter_after_2000:latest
    networks:
      - movies_net
  group-by-country-sum-1:
    build:
      context: .
      dockerfile: group_by/group_by_country_sum/Dockerfile
    container_name: group-by-country-sum-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=group-by-country-sum.1
      - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=movies.group_by_country_sum
    image: group_by_country_sum:latest
    networks:
      - movies_net
  group-by-movie-average-1:
    build:
      context: .
      dockerfile: group_by/group_by_movie_average/Dockerfile
    container_name: group-by-movie-average-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=group-by-movie-average.1
      - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=movies.group_by_movie_average
    image: group_by_movie_average:latest
    networks:
      - movies_net
  group-by-actor-count-1:
    build:
      context: .
      dockerfile: group_by/group_by_actor_count/Dockerfile
    container_name: group-by-actor-count-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=group-by-actor-count.1
      - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=movies.group_by_actor_count
    image: group_by_actor_count:latest
    networks:
      - movies_net
  group-by-overview-average-1:
    build:
      context: .
      dockerfile: group_by/group_by_overview_average/Dockerfile
    container_name: group-by-overview-average-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=group-by-overview-average.1
      - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=movies.group_by_overview_average
    image: group_by_overview_average:latest
    networks:
      - movies_net
  master-group-by-country-sum-1:
    build:
      context: .
      dockerfile: master_group_by/master_group_by_country_sum/Dockerfile
    container_name: master-group-by-country-sum-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=movies.group_by_country_sum
      - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=master.country_sum
    image: master_group_by_country_sum:latest
    networks:
      - movies_net
  master-group-by-movie-average-1:
    build:
      context: .
      dockerfile: master_group_by/master_group_by_movie_average/Dockerfile
    container_name: master-group-by-movie-average-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=movies.group_by_movie_average
      - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=master.movie_average
    image: master_group_by_movie_average:latest
    networks:
      - movies_net
  master-group-by-actor-count-1:
    build:
      context: .
      dockerfile: master_group_by/master_group_by_actor_count/Dockerfile
    container_name: master-group-by-actor-count-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=movies.group_by_actor_count
      - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=master.actor_count
    image: master_group_by_actor_count:latest
    networks:
      - movies_net
  master-group-by-overview-average-1:
    build:
      context: .
      dockerfile: master_group_by/master_group_by_overview_average/Dockerfile
    container_name: master-group-by-overview-average-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=movies.group_by_overview_average
      - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=query5.results
    image: master_group_by_overview_average:latest
    networks:
      - movies_net
  machine-learning-1:
    build:
      context: .
      dockerfile: machine_learning/Dockerfile
    container_name: machine-learning-1
    depends_on:
      - rabbitmq
    entrypoint: python main.py
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=movies.client_handler
      - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=movies.ml.router
    image: machine_learning:latest
    networks:
      - movies_net
  top-five-country-budget-1:
    build:
      context: .
      dockerfile: topn/top_five_country_budget/Dockerfile
    container_name: top-five-country-budget-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=master.country_sum
      - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=query2.results
    image: top_five_country_budget:latest
    networks:
      - movies_net
  top-ten-cast-movie-1:
    build:
      context: .
      dockerfile: topn/top_ten_cast_movie/Dockerfile
    container_name: top-ten-cast-movie-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=master.actor_count
      - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=query4.results
    image: top_ten_cast_movie:latest
    networks:
      - movies_net
  # join-movie-ratings-1:
  #   build:
  #     context: .
  #     dockerfile: joins/join_movie_ratings/Dockerfile
  #   container_name: join-movie-ratings-1
  #   depends_on:
  #     - rabbitmq
  #   entrypoint: ./run_worker
  #   environment:
  #     - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
  #     - CLI_LOG_LEVEL=info
  #     - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=join-movie-ratings.movies.router.1,join-movie-ratings.ratings.router.1
  #     - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=join_movie_ratings.router
  #   image: join_movie_ratings:latest
  #   networks:
  #     - movies_net
  # join-movie-credits-1:
  #   build:
  #     context: .
  #     dockerfile: joins/join_movie_credits/Dockerfile
  #   container_name: join-movie-credits-1
  #   depends_on:
  #     - rabbitmq
  #   entrypoint: ./run_worker
  #   environment:
  #     - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
  #     - CLI_LOG_LEVEL=info
  #     - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=join-movie-credits.movies.router.1,join-movie-credits.credits.router.1
  #     - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=join_movie_credits.router
  #   image: join_movie_credits:latest
  #   networks:
  #     - movies_net
  first-and-last-1:
    build:
      context: .
      dockerfile: topn/first_and_last/Dockerfile
    container_name: first-and-last-1
    depends_on:
      - rabbitmq
    entrypoint: ./run_worker
    environment:
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_LOG_LEVEL=info
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=master.movie_average
      - CLI_WORKER_EXCHANGE_OUTPUT_ROUTINGKEYS=query3.results
    image: first_and_last:latest
    networks:
      - movies_net
  router-1:
    build:
      context: .
      dockerfile: router/Dockerfile
    container_name: router-1
    entrypoint: /run_worker
    image: router:latest
    networks: *id001
    depends_on:
      - rabbitmq
    environment:
      - CLI_LOG_LEVEL=info
      - CLI_WORKER_EXCHANGE_INPUT_ROUTINGKEYS=movies.after_2000,ratings.client-handler.router,credits.client-handler.router,movies.filter_only_one_country.router,movies.ml.router,join_movie_ratings.router,join_movie_credits.router
      - CLI_WORKER_BROKER=amqp://guest:guest@rabbitmq:5672/
      - CLI_WORKER_OUTPUT_ROUTINGKEYS_JOIN-MOVIE-CREDITS=join-movie-credits.1
      - CLI_WORKER_OUTPUT_ROUTINGKEYS_JOIN-MOVIE-RATINGS=join-movie-ratings.1
      - CLI_WORKER_OUTPUT_ROUTINGKEYS_GROUP-BY-OVERVIEW-AVERAGE=group-by-overview-average.1
      - CLI_WORKER_OUTPUT_ROUTINGKEYS_GROUP-BY-ACTOR-COUNT=group-by-actor-count.1
      - CLI_WORKER_OUTPUT_ROUTINGKEYS_GROUP-BY-MOVIE-AVERAGE=group-by-movie-average.1
      - CLI_WORKER_OUTPUT_ROUTINGKEYS_GROUP-BY-COUNTRY-SUM=group-by-country-sum.1
